require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - rubocop-rspec.gemspec
    - Rakefile
    - '**/*.rake'
    - spec/**/*.rb

Style/FileName:
  Exclude:
    - lib/rubocop-rspec.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

RSpec/ExampleLength:
  Max: 19

RSpec/DescribeClass:
  Exclude:
    - spec/project/**/*.rb
