sudo: false
cache: bundler
language: ruby

rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.1.0.0
  - rbx-3

env:
  # this doesn't do anything for MRI or RBX, but it doesn't hurt them either
  # for JRuby, it enables us to get more accurate coverage data
  - JRUBY_OPTS="--debug"

matrix:
  allow_failures:
    - rvm: jruby-9.1.0.0
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true

addons:
  code_climate:
    repo_token: 40adf93a016e2779eef43dce8f16ca10098ed9f498522e87c8bc94cf14f3e977

before_install: gem update --remote bundler
script: bundle exec rake
