sudo: false
cache: bundler
language: ruby

rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

addons:
  code_climate:
    repo_token: 40adf93a016e2779eef43dce8f16ca10098ed9f498522e87c8bc94cf14f3e977

before_install: gem update --remote bundler
script: bundle exec rake
