steps:
  - command: "build/run 2.1.10 spec"
    label: ":rspec: RSpec (2.1)"
    agents:
      - queue=elastic

  - command: "build/run 2.2.5 spec"
    label: ":rspec: RSpec (2.2)"
    agents:
      - queue=elastic

  - command: "build/run 2.3.1 spec"
    label: ":rspec: RSpec (2.3)"
    agents:
      - queue=elastic

  - command: "build/run 2.4.0 spec"
    label: ":rspec: RSpec (2.4)"
    agents:
      - queue=elastic

  - command: "build/run 2.1.10 internal_investigation"
    label: ":rubocop: RuboCop (2.1)"
    agents:
      - queue=elastic

  - command: "build/run 2.2.5 internal_investigation"
    label: ":rubocop: RuboCop (2.2)"
    agents:
      - queue=elastic

  - command: "build/run 2.3.1 internal_investigation"
    label: ":rubocop: RuboCop (2.3)"
    agents:
      - queue=elastic

  - command: "build/run 2.4.0 internal_investigation"
    label: ":rubocop: RuboCop (2.4)"
    agents:
      - queue=elastic

  - command: "build/run 2.3.1 confirm_config"
    label: ":scroll: Configuration"
    agents:
      - queue=elastic
