---
AllCops:
  RailsDdd:
    Patterns:
    - app/concepts/**/*.rb

RailsDdd/Namespacing:
  Description: Check that code conforms to namespacing standards
  Enabled: true
  StyleGuide: http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RailsDdd/Namespacing
